### ISSUE TITLE
Persistent Volumes for gitlab - what to do if you run out of space?

### ISSUE THREAD

**Issue by pjatacsukb** [lwolf/gitlab-chart#1]
What would a be good approach to fix storage issues when your services run out of the presistent volume free space?

For example I have a gitlab service running on kubernetes installed with the helm chart. I have used the default settings, but now I ran out of free space (theoretically atm, but its inevitable at some point) for gitlab. What would be the ideal approach to fix this issue?

Is there anyway I can increase the PV in size?
Should I somehow backup the gitlab data, recreate it with more storage?
Can I somehow backup and restore data from PV-s so there is no dataloss? 
Thank you for your answers, Bence Pjatacsuk

**Comment by lwolf** [comment]
Hi.
Resizing of the volumes depends on what cluster you use. 
For example, GCE supports manual resize of the volumes. https://cloud.google.com/compute/docs/disks/add-persistent-disk#resize_pd

In the case of gitlab, it's pretty easy to backup/restore its data. I did it recently.
Check out documentation in docker-gitlab repository:
https://github.com/sameersbn/docker-gitlab#maintenance

**Comment by pjatacsukb** [comment]
Thank you for your answer, we are using kubernetes on our own "baremetal" VM-s, so sadly we have to do lot of things by the hard way.

Manual backup / restore than the way to go!
