### ISSUE TITLE
Deployment on Azure

### ISSUE THREAD

**Issue by dewolfs** [lwolf/gitlab-chart#11]
Hi,

I'm trying out this chart on a Kubernetes cluster running in Microsoft Azure.
Changed the "slow" storageclass to "default.
![overview](https://user-images.githubusercontent.com/13407615/29108905-34edd9ee-7ce1-11e7-9b4d-a66f2f590a84.png)

![pods](https://user-images.githubusercontent.com/13407615/29108922-41689632-7ce1-11e7-93dd-c13d7b19499b.png)
![pvc](https://user-images.githubusercontent.com/13407615/29108926-45833470-7ce1-11e7-8a03-5117a845470b.png)
![gitlaberror](https://user-images.githubusercontent.com/13407615/29108930-4971fd78-7ce1-11e7-8d92-c47e1f782949.png)
![registryerror](https://user-images.githubusercontent.com/13407615/29108934-4cb6b334-7ce1-11e7-80f5-f5786926ea03.png)

All pvc are mounted.

I want to get Gitlab auto-deploy running with d2d image. for this the container registry of Gitlab is required.  I got gitlab and the runner working via seperate charts.  As Kubernetes is new to me, can somebody tell me how to create the gitlab container registry?  Do I need a nginx-ingress?

**Comment by lwolf** [comment]
Here is the detailed post about deploying gitlab using this chart.
http://blog.lwolf.org/post/fully-automated-gitlab-installation-on-kubernetes-including-runner-and-registry/
