### ISSUE TITLE
Issue with the 'helm dep build' command

### ISSUE THREAD

**Issue by Thumpermat** [lwolf/gitlab-chart#13]
I'm using the instructions described here:

https://blog.lwolf.org/post/fully-automated-gitlab-installation-on-kubernetes-including-runner-and-registry/

When I run the `helm dep build` command, I get the following error:

`Error: requirements.lock is out of sync with requirements.yaml`

Should I run a `helm dep update`before ?

**Comment by lwolf** [comment]
Hi,
Yes, looks like the post is a bit out of sync with the repo. You need to run `helm dep update` in case of that error.

**Comment by Thumpermat** [comment]
I sent you a mail on gmail with a few issues I have, but I don't think they
belong on GitHub.

**Comment by lwolf** [comment]
Got it, had a bit of a queue of emails. 
Looks like you've got it figured with helm dep, so I'm closing it.
