### ISSUE TITLE
minio fails to start

### ISSUE THREAD

**Issue by weisjohn** [lwolf/gitlab-chart#17]
my system:

```bash
λ minikube version
minikube version: v0.26.1
λ k version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
λ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

I followed the steps in the readme, and after 30 minutes, this issue didn't resolve itself.

```
λ k logs gitlab-minio-855f48d9c-9fmpd
minio: <ERROR> Cannot validate configuration file. Error: bad config version, expected: 14
```

Any ideas? Please advise.

**Comment by lwolf** [comment]
Could you post the content of dependencies, it's in `charts` subfolder of the chart.
It should contain something like: minio-***.tgz, postgresql-***.tgz, etc.
And also, did you change something in the values.yaml?

**Comment by weisjohn** [comment]
@lwolf thanks for the quick reply.  Where should I find the `charts` subfolder?  I added the repo via `helm repo add lwolf-charts http://charts.lwolf.org`, not cloned locally. I can do that if you'd like. In the meantime, here's the contents of `~/.helm` incase that helps:

```
λ tree ~/.helm/
/Users/johnweis/.helm/
├── cache
│   └── archive
│       ├── gitlab-0.2.8.tgz
│       ├── gitlab-ce-0.2.1.tgz
│       ├── gitlab-ee-0.2.1.tgz
│       ├── gitlab-omnibus-0.1.37.tgz
│       ├── mariadb-4.1.1.tgz
│       └── mysql-0.6.0.tgz
├── plugins
├── repository
│   ├── cache
│   │   ├── gitlab-index.yaml
│   │   ├── local-index.yaml -> /Users/johnweis/.helm/repository/local/index.yaml
│   │   ├── lwolf-charts-index.yaml
│   │   └── stable-index.yaml
│   ├── local
│   │   └── index.yaml
│   └── repositories.yaml
└── starters
```

I have made very small tweaks to the sample `values-test.yaml`, just links like:

```
minio:
  # ...
  persistence:
    size: 5Gi  # instead of 10Gi
```

I can try it again with regular values setup.

**Comment by weisjohn** [comment]
after cloning the repo and `helm dep update`, here are the versions:

```
λ ls
minio-0.1.0.tgz      postgresql-0.6.0.tgz redis-0.7.0.tgz      registry-0.2.0.tgz   runner-0.4.1.tgz
```

**Comment by weisjohn** [comment]
same issue against the newly created mini pod:

```
λ k logs gitlab-minio-855f48d9c-zwhwg
minio: <ERROR> Cannot validate configuration file. Error: bad config version, expected: 14
```

**Comment by lwolf** [comment]
I was able to reproduce the issue using `test-values.yaml`. 
looking into it...

**Comment by weisjohn** [comment]
@lwolf thank you for the confirmation! let me know if there's anything I can do to help test.

**Comment by lwolf** [comment]
@weisjohn I pushed the commit with updated version the minio to master. Also, I made `GITHUB_HOST` and `GITLAB_ROOT_EMAIL` required to avoid confusion. Since a lot of people are trying to install the chart with the default value of `gitlab.example.com` and it does not work.

Would be great if you can test it. Otherwise, I'll be able to do it, hopefully, tomorrow evening.

**Comment by weisjohn** [comment]
@lwolf thanks for the update. I got it to work on my machine, however, I had to make some tweaks to get it to work on minikube. Would it help if I submitted a PR for others?

**Comment by lwolf** [comment]
that would be great, could you post here what exactly did you change first? may-be it will make sense to create another example-values.yaml specifically for minikube

**Comment by weisjohn** [comment]
```
resources:
  requests:
    memory: 512Mi
persistence:
  size: 2Gi

postgresql:
  memory: 256Mi
  persistence:
    size: 1Gi

redis:
  resources:
    requests:
      memory: 256Mi
  persistence:
    size: 1Gi

minio:
  persistence:
    size: 1Gi

config:
  GITLAB_HTTPS: "true"
```

**Comment by lwolf** [comment]
I see, reducing resource requirements totally make sense.
But GITLAB_HTTPS is already set by the default values.yaml inside the chart, so it does nothing.
Could you please submit PR with this changes to the `examples/values-test.yaml`, that would help people who start with the minikube.

**Comment by weisjohn** [comment]
@lwolf I actually had to set it to false, which is different than the previous blurb I sent. I'll submit a PR w/ these values in a minikube.yml w/ a note in the documentation to help explain how to use both files.

**Comment by weisjohn** [comment]
actually, on second thought, based on one of your commit history comments, I'll put it in `values-test.yaml` as you said. Thanks!
