### ISSUE TITLE
Blog/Instructions not working

### ISSUE THREAD

**Issue by michaelerobertsjr** [lwolf/gitlab-chart#5]
I am trying to use your excellent resource, but I am finding that the blog instructions are not quite working for me.  

I am getting several errors and I have tried to figure out what files belong where, to no avail.  Could you confirm that the blog/instructions are still correct?

When I clone the project, cd into the project, and then run:

```sh
cp chart/values.yaml values-test.yaml 
```

It will error off because there is not a chart directory in the main directory.  So.... I though it may be: 

```sh
cp gitlab/values.yaml values-test.yaml
```

Then it gives a new error when I do a dry run: `Error: no Chart.yaml exists in directory ...`

So I am wondering if there are a few changes that are not reflected yet in the docs??

**Comment by lwolf** [comment]
Hi
Looks like I did rename directory from chart to gitlab when added examples.

```
$ git clone https://github.com/lwolf/gitlab-chart
$ cd gitlab-chart/gitlab
$ cp values.yaml values-test.yaml
$ helm install -f values-test.yaml .
```

**Comment by michaelerobertsjr** [comment]
That ends up getting me a little further, however I now get an error:

Error: found in requirements.yaml, but missing in charts/ directory: redis, postgresql, minio, runner, registry

**Comment by lwolf** [comment]
Yep, you need to pull dependencies. That was not needed at the moment of writing...

```
helm dep build
```

**Comment by michaelerobertsjr** [comment]
That is asking for a repository...

Error: no repository definition for http://charts.lwolf.org/, http://charts.lwolf.org/. Try 'helm repo add'

**Comment by lwolf** [comment]
Yes, some charts are hosted in my github repository.
https://github.com/lwolf/kube-charts

```
$ helm repo add lwolf-charts http://charts.lwolf.org
"lwolf-charts" has been added to your repositories
```

**Comment by michaelerobertsjr** [comment]
Great! That looks like it will work.  Got positive looking results from:

```
helm install -f values-test.yaml . --namespace=gitlab --debug --dry-run
```

Thanks!  I will make sure I can do a complete install, and then I'll open a pull request to update your README.md tomorrow if it all works.  This looks very promising.

**Comment by lwolf** [comment]
Great, thanks

**Comment by michaelerobertsjr** [comment]
Seem to have an issue with the Registry Service:

[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "plinking-snake-gitlab-data", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "plinking-snake-gitlab-data", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "plinking-snake-gitlab-data", which is unexpected.]
MountVolume.SetUp failed for volume "kubernetes.io/secret/56d83e7f-3bfb-11e7-9bb1-42010a8a01ad-certs" (spec.Name: "certs") pod "56d83e7f-3bfb-11e7-9bb1-42010a8a01ad" (UID: "56d83e7f-3bfb-11e7-9bb1-42010a8a01ad") with: secrets "registry-server-tls" not found

Everything else seems to come up ok... any thoughts?

**Comment by lwolf** [comment]
**`plinking-snake-gitlab-data`** - check that your storages are working, that PV and PVC could be created. Your cluster have to have some dynamic storage provisioning. Otherwise you need to hardcode your PV/PVC.
```
persistence:
  enabled: true
  size: 10Gi
  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass: ""
  accessMode: ReadWriteOnce
```

**secrets "registry-server-tls" not found** - could be due to disabled ingress or not using kube-lego. Docker registry needs SSL to work properly. I'm using lets encrypt for this.
If you do not use kube-lego you will have to create and put TLS secret manually to make it work

**Comment by oliverkane** [comment]
@michaelerobertsjr , sorry for the late reply.  I had the same error as you above. Looks like it just takes the cluster a bit to provision dynamically allocated storage.  What platform are you using?  I was on GCE, and it takes about 5 mins to provision the storage.

**Comment by tengzhexiao** [comment]
I was pending in volume create index over 20 mins ,I don't know what's wrong...
