### ISSUE TITLE
couldn't find type: v1beta1.Job

### ISSUE THREAD

**Issue by msvechla** [lwolf/gitlab-chart#6]
Hello, 

I'm getting the following error when installing the chart:
`Error: error validating "": error validating data: couldn't find type: v1beta1.Job`

I guess it is related to the file: gitlab/charts/runner/templates/registrator.yaml

Kubelet Version:
v1.6.2+coreos.0

**Comment by msvechla** [comment]
changing it to:
`apiVersion: batch/v1` worked. Can you update this in the packaged version?
Thank you!

**Comment by lwolf** [comment]
Hi, this chart is not yet migrated to 1.6. 
There were many changes between 1.5->1.6 in Kubernetes and jobs are one of them.

v1beta1.Job -> batch/v1.Job should work, but I think there will be more issues
