### ISSUE TITLE
Running this on Azure fails.

### ISSUE THREAD

**Issue by martell** [lwolf/gitlab-chart#9]
`kubectl describe po/cautious-quail-gitlab-1587105889-bt3pq`
reveals the gitlab pod is left `Pending` with persistentvolumeclaim "gitlab-nas-backup" not found

`kubectl get all`
```
azureuser@k8s-master-0:~$ kubectl get all
NAME                                            READY     STATUS     RESTARTS   AGE
po/cautious-quail-gitlab-1587105889-bt3pq       0/1       Pending    0          16m
po/cautious-quail-minio-3713786803-q281t        1/1       Running    0          27m
po/cautious-quail-postgresql-4157173895-hc9kt   1/1       Running    0          27m
po/cautious-quail-redis-3064224060-vdg85        1/1       Running    0          27m
po/cautious-quail-registry-3593718853-kj170     1/1       Running    0          27m
po/cautious-quail-runner-64w3h                  0/1       Init:0/1   0          27m
NAME                            CLUSTER-IP    EXTERNAL-IP     PORT(S)                                   AGE
svc/cautious-quail-gitlab       10.0.51.102   <hidden>    22:31892/TCP,80:31515/TCP,443:32371/TCP   27m
svc/cautious-quail-minio-svc    10.0.176.24   <hidden>   9000:32059/TCP                            27m
svc/cautious-quail-postgresql   10.0.20.95    <none>          5432/TCP                                  27m
svc/cautious-quail-redis        10.0.145.79   <none>          6379/TCP                                  27m
svc/cautious-quail-registry     10.0.14.15    <none>          5000/TCP                                  27m
svc/kubernetes                  10.0.0.1      <none>          443/TCP                                   19h
NAME                         DESIRED   SUCCESSFUL   AGE
jobs/cautious-quail-runner   1         0            27m
NAME                               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/cautious-quail-gitlab       1         1         1            0           27m
deploy/cautious-quail-minio        1         1         1            1           27m
deploy/cautious-quail-postgresql   1         1         1            1           27m
deploy/cautious-quail-redis        1         1         1            1           27m
deploy/cautious-quail-registry     1         1         1            1           27m
NAME                                      DESIRED   CURRENT   READY     AGE
rs/cautious-quail-gitlab-1587105889       1         1         0         27m
rs/cautious-quail-minio-3713786803        1         1         1         27m
rs/cautious-quail-postgresql-4157173895   1         1         1         27m
rs/cautious-quail-redis-3064224060        1         1         1         27m
rs/cautious-quail-registry-3593718853     1         1         1         27m
```

@lwolf any hints? :)

**Comment by lwolf** [comment]
Yes, you're probably using not the latest version. 
It was one commit where I accidentally pushed my custom config :)

**Comment by martell** [comment]
I followed these steps
`helm repo add lwolf-charts http://charts.lwolf.org`
`curl https://raw.githubusercontent.com/lwolf/gitlab-chart/master/gitlab/values.yaml -o values-test.yaml`
Edited the yaml for my ingress and keys etc.

also note for other people trying to do this that unless you enable the runner or registry the whole thing fails to deploy
example
```
registry:
  enabled: true
```
Then I ran `helm install -f values-test.yaml lwolf-charts/gitlab`

Is there some steps I am missing to get the latest?

**Comment by lwolf** [comment]
Please try to run `helm repo update`
and then 
`helm search lwolf-charts`

**Comment by martell** [comment]
```
lwolf-charts/gitlab             0.2.5   GitLab Community Edition
lwolf-charts/gitlab-registry    0.2.0   Gitlab docker registry
lwolf-charts/gitlab-runner      0.2.0   GitLab-ci runner
lwolf-charts/plex               0.1.1   Plex
lwolf-charts/registry           0.2.0   Gitlab docker registry
lwolf-charts/runner             0.3.0   GitLab-ci runner
lwolf-charts/stolon             0.1.1   Stolon Helm Chart for Kubernetes.
```
Are the values.

Will get back to you shortly with a status update.
Azure persistent disks are flaky when you try to `helm delete`
So I have to kill the whole cluster and set it up again

**Comment by lwolf** [comment]
`lwolf-charts/gitlab             0.2.5   GitLab Community Edition` is the latest. 

Did not use azure, but can't you just delete persistent disks from web-ui ?

**Comment by martell** [comment]
> Did not use azure, but can't you just delete persistent disks from web-ui ?

The ui fails to delete them when there was a previous request to delete and it never completed properly leaving it in a broken state. That is an issue for the acs-engine team to deal with I guess.

Sorry for the delay, it takes a while to do that each time :)
Anyway @lwolf still have the same problem 
`FailedScheduling        persistentvolumeclaim "gitlab-nas-backup" not found`

Your partials have `_backup_gcs.yaml` and `_backup_gcs.yaml`.
Could that have anything to do with it?

**Comment by lwolf** [comment]
Hmmm. that is really strange.  I fetched chart from the repo and it still has this lines.
Sorry about that :)

Lets fix your deploy, and then I'll update repository.
You do not need to destroy your cluster. just do these things:

```
$ helm fetch lwolf-charts/gitlab
$ tar xvf gitlab-0.2.5.tgz
$ cd gitlab
$ vim templates/deployment.yaml
#### find and delete this lines
....
        - name: gitlab-backup
          mountPath: /home/git/data/backups
....
      - name: gitlab-backup
        persistentVolumeClaim:
          claimName: gitlab-nas-backup
....
####
```
after this you can upgrade your deployment
```
$ helm ls
NAME              	REVISION	UPDATED                 	STATUS  	CHART           	NAMESPACE
########
 find release name of your gitlab
###########
$ helm upgrade -f values-test.yaml <release-name> .    # <<<  mind dot at the end.
```
This should work

**Comment by martell** [comment]
Sorry for the delay, my time is limited around work.
I managed to delete and get this running with the 0.2.6 chart :)
Thanks for the update.

I managed to get it running on k8s 1.7.2 on Azure with rbac :)
Which should be released in the coming weeks
